version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: prod_user
      RABBITMQ_DEFAULT_PASS: prod_password
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      retries: 3
      start_period: 10s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - queue-app-network

  app:
    build:
      context: .
      target: prod
    image: queue-api-app:latest
    ports:
      - '3000:3000'
    environment:
      - AWS_REGION=us-east-1
      - RABBITMQ_URL=amqp://prod_user:prod_password@rabbitmq:5672
      # Use real AWS SQS endpoint in production
      - SQS_ENDPOINT=https://sqs.us-east-1.amazonaws.com
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health'] # Adjust the endpoint as per your app
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - queue-app-network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  queue-app-network:
